name: vlm_point_gemma_it
wandb_enabled: false
loader:
  source: labels/cb_412.json
  kwargs:
    image_dir: data/
models: {}
stages:
  - inputs:
      - [Image, human]
      - [TargetNoun, human]
    output: ObjectCoordinates
    processor: VLMLocateProcessor
    kwargs:
      model_id: "google/gemma-4-E4B-it"
  - inputs:
      - [ObjectCoordinates, model]
    output: VLMCount
    processor: CoordinateCountProcessor
  - inputs:
      - [Answer, human]
      - [VLMCount, model]
    output: EvalResult
    processor: EvaluatorProcessor
