name: vlm_mask_score_gemma
wandb_enabled: false
loader:
  source: labels/cb_412.json
  kwargs:
    image_dir: data/
models: {}
stages:
  - inputs:
      - [Image, human]
      - [Question, human]
    output: MaskScores
    processor: VLMMaskScoreProcessor
    kwargs:
      model_id: "google/gemma-4-E4B-it"
  - inputs:
      - [MaskScores, model]
    output: VLMCount
    processor: BestCountProcessor
  - inputs:
      - [Answer, human]
      - [VLMCount, model]
    output: EvalResult
    processor: EvaluatorProcessor
